// On first row, we write 0.Every other row is generated by replacing teh previous row 0 with 01 and 1 with 10

// Given row number N and an index k, return kth symbol

// Brute Force
// Generate Nth row and get kth index
